### ISSUE TITLE
Same problem of "backdoor federated learning"

### ISSUE THREAD

**Issue by Growdy** [6sephiruth/21_CSRC#1]
Sorry for putting the issue here, but I can't contact you by email. I saw your issue under the code of "how to backdoor federated learning".　I meet the same problem as you, but I can't solve it.  I don't know how to tweak the params file. Can you help me?

current path: saved_models/model_image_May.03_22.55.09
Loading data
Files already downloaded and verified
We use following environment for graphs:  ppdl_experiment
Selected models: [65, 7, 66, 27, 80, 93, 50, 34, 4, 52]
There are 0 adversaries in the training.
time spent on training: 36.929800510406494
Traceback (most recent call last):
  File "training.py", line 671, in <module>
    weight_accumulator=weight_accumulator, epoch=epoch)
  File "D:\should\backdoor_federated_learning-master\backdoor_federated_learning-master\helper.py", line 211, in average_shrink_models
    data.add_(update_per_layer)
RuntimeError: result type Float can't be cast to the desired output type Long

**Comment by cat-6sephiruth** [comment]
Hello, the progress has been going on for a long time, so I think you need to tell me in detail what the symptoms are.
call the **6sephiruth@gmail.com**
In addition, it would be better if you refer to this site.   [(https://github.com/AI-secure/DBA)]
Upgrade the paper above? One paper, and it works fine with that code.
I didn't understand what your problem was.
If you tell me the details, I'll help you.
